version: '3'

vars:
  MODULE: github.com/zeromicro/go-zero/tools/goctl

tasks:
  format:
    cmds:
      - task: goimports
        vars:
          CLI_ARGS: .
  goimports:
    deps:
      - setup:goimports
    cmds:
      - goimports -local "{{.MODULE}}" -w {{.CLI_ARGS}}

  setup:
    deps:
      - setup:local
    cmds:
      - go install github.com/evilmartians/lefthook@latest
      - lefthook install
  setup:goimports:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@v0.4.0
    status:
      - test -f goimports
  setup:local:
    deps:
      - setup:goimports


