name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
          cache: true
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Lint
        run: |
          go vet -stdmethods=false $(go list ./...)

          go mod tidy
          if ! test -z "$(git status --porcelain)"; then
            echo "Please run 'go mod tidy'"
            exit 1
          fi

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Test Race
        run: |
          # race test ignore packages which impacted by redis v9,
          # we can remove it after redis v9 fix race issue https://github.com/redis/go-redis/issues/2557
          go test -race $(go list ./... | grep -v -e /core/stores/redis -e /core/stores/sqlc -e /core/stores/monc -e /core/stores/kv -e /core/stores/cache -e /core/bloom -e /core/limit -e /zrpc/internal/serverinterceptors -e /zrpc/internal/auth -e /zrpc$)

      - name: Codecov
        uses: codecov/codecov-action@v3

  test-win:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          # use 1.18 to guarantee Go 1.18 compatibility
          go-version: 1.18
          check-latest: true
          cache: true

      - name: Test
        run: |
          go mod verify
          go mod download
          go test ./...
          cd tools/goctl && go build -v goctl.go
